// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA73wRwJqiP7VMFOYEbL1GWGDKWSispZS8',
    appId: '1:473772010815:web:2f8c544ad7acbbb621378a',
    messagingSenderId: '473772010815',
    projectId: 'registration-app-cc96b',
    authDomain: 'registration-app-cc96b.firebaseapp.com',
    storageBucket: 'registration-app-cc96b.firebasestorage.app',
    measurementId: 'G-4C0BV7NL2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuiGCjw6yDBs2Ym26-GfTFHxGifJYNBQI',
    appId: '1:473772010815:android:f68f32b8f46efa6621378a',
    messagingSenderId: '473772010815',
    projectId: 'registration-app-cc96b',
    storageBucket: 'registration-app-cc96b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGyUF9E4UeVCL3Zmpa_D2CScJCcqqp05s',
    appId: '1:473772010815:ios:088e390ec1b3b53821378a',
    messagingSenderId: '473772010815',
    projectId: 'registration-app-cc96b',
    storageBucket: 'registration-app-cc96b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGyUF9E4UeVCL3Zmpa_D2CScJCcqqp05s',
    appId: '1:473772010815:ios:088e390ec1b3b53821378a',
    messagingSenderId: '473772010815',
    projectId: 'registration-app-cc96b',
    storageBucket: 'registration-app-cc96b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA73wRwJqiP7VMFOYEbL1GWGDKWSispZS8',
    appId: '1:473772010815:web:8b7028ca0d72435621378a',
    messagingSenderId: '473772010815',
    projectId: 'registration-app-cc96b',
    authDomain: 'registration-app-cc96b.firebaseapp.com',
    storageBucket: 'registration-app-cc96b.firebasestorage.app',
    measurementId: 'G-SL0Z27M2QM',
  );
}
